Repository kymckay/F28WP-Project, pull requests merged in 2020-11, with the labels that each got.

#18 Initial server setup
  package-lock.json
  package.json
  public/AC.png
  public/ES.png
  public/KM.png
  public/MSF.png
  public/T.png
  public/aboutus.html
  public/css/main.css
  public/css/menu.css
  public/index.html
  public/play.html
  public/signup.html
  server/server.js
Labels: enhancement, organisational

#23 Implement all of the initial game setup
  .editorconfig
  .eslintrc.json
  .travis.yml
  README.md
  package-lock.json
  package.json
  public/assets/sprites/asteroid.png
  public/assets/sprites/asteroid.svg
  public/assets/sprites/explosion.png
  public/assets/sprites/explosion.svg
  public/assets/sprites/laser.png
  public/assets/sprites/ship-player.svg
  public/assets/sprites/ship.svg
  public/assets/sprites/spaceship.png
  public/css/common.css
  public/css/game.css
  public/css/gameObjects.css
  public/css/hud.css
  public/css/menu.css
  public/index.html
  public/play.html
  public/src/actionMap.js
  public/src/classes/asteroid.js
  public/src/classes/entity.js
  public/src/classes/projectile.js
  public/src/classes/ship.js
  public/src/collision.js
  public/src/controller.js
  public/src/coordinates.js
  public/src/game.js
  public/src/gameObject.js
  public/src/hud.js
  public/src/particle.js
  public/src/physicsObject.js
  public/src/vector.js
  resources.txt
  server/classes/asteroid.js
  server/classes/entity.js
  server/classes/lobby.js
  server/classes/ship.js
  server/classes/world.js
  server/server.js
  server/starfield.js
Labels: cat/game logic, cat/networking, cat/rendering, kind/enhancement

#29 Server simulation
  public/css/game.css
  public/src/classes/asteroid.js
  public/src/classes/entity.js
  public/src/classes/projectile.js
  public/src/classes/ship.js
  public/src/coordinates.js
  public/src/game.js
  server/classes/asteroid.js
  server/classes/entity.js
  server/classes/lobby.js
  server/classes/projectile.js
  server/classes/ship.js
  server/classes/world.js
  server/server.js
Labels: cat/networking, cat/rendering, kind/enhancement

#35 Update readme to reflect project developments
  CONTRIBUTING.md
  README.md
Labels: cat/documentation

#39 Tweak ship, asteroid and projectile behaviour
  server/classes/asteroid.js
  server/classes/projectile.js
  server/classes/ship.js
  server/classes/world.js
Labels: cat/simulation, kind/enhancement

#37 Render explosions when ships and asteroids die
  public/assets/sprites/explosion.svg
  public/css/game.css
  public/src/game.js
Labels: cat/rendering, kind/enhancement

#40 Render world boundaries for clients
  public/css/common.css
  public/css/game.css
  public/css/hud.css
  public/play.html
  public/src/game.js
Labels: cat/rendering, kind/enhancement

#42 Allow all entities to wrap
  server/classes/entity.js
  server/classes/projectile.js
  server/classes/ship.js
  server/classes/world.js
Labels: cat/simulation, kind/enhancement

#45 Add collision detection and player respawn
  .eslintrc.json
  public/src/game.js
  public/src/hud.js
  server/classes/lobby.js
  server/classes/projectile.js
  server/classes/ship.js
  server/classes/world.js
Labels: cat/rendering, cat/simulation, kind/enhancement

#46 Handle player disconnection elegantly
  server/classes/lobby.js
  server/classes/world.js
Labels: cat/simulation, kind/enhancement

#47 Set up Heroku automatic deployment
  CONTRIBUTING.md
  Procfile
  README.md
  package.json
  server/server.js
Labels: kind/enhancement, kind/organisational

#48 Implement end game handling
  public/css/hud.css
  public/play.html
  public/src/game.js
  public/src/hud.js
  server/classes/lobby.js
Labels: cat/rendering, cat/simulation

#28 Database Implementation
  .gitignore
  README.md
  package-lock.json
  package.json
  public/src/menu.js
  server/classes/projectile.js
  server/database.js
  server/db_template.json
  server/server.js
Labels: cat/database, kind/enhancement

#50 Fix database connection errors in live environment
  server/database.js
Labels: cat/database
